# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Paul Roub - Link(s) in Bio
email: paul@roub.net
description: >- # this means to ignore newlines until "baseurl:"
    A collection of links to things I may have mentioned.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://links.roub.net/" # the base hostname & protocol for your site, e.g. http://example.com
github_username: paulroub
subheads:
    - A collection of links to things I may have mentioned.

tiktok_username: "paulroub"
instagram_username: "paulroub"
threads_username: "paulroub"
mastodon_username: "@paulroub@indieweb.social"
bluesky_username: "paul.roub.net"
youtube_username: "PaulRoub"
plausible_io: "links.roub.net"

# Build settings
theme: jekyll-theme-linky
plugins:
    - jekyll-feed

collections:
    - links

feed:
    collections:
        - links

linky:
    body_background: "#FFF"
    body_foreground: "#000"
    button_foreground: "#F0F0F0"
    button_background: "#006"
    social_button_color: "#666"
    add_rel_me_links: true
